apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask   # predictable name
spec:
  type: NodePort                    # expose externally
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000               # fixed port for easy access

